// src/adapters/react/components/Timeline.tsx
/**
 * React Timeline Component
 */

import React, { CSSProperties } from 'react';
import { TimelineConfig, TimelineEvent } from '../../../types';
import { useTimeline } from '../hooks/useTimeline';

export interface TimelineProps {
  events: TimelineEvent[];
  orientation?: 'horizontal' | 'vertical';
  renderType?: 'canvas' | 'svg';
  width?: number;
  height?: number;
  className?: string;
  style?: CSSProperties;
  onReady?: (instance: any) => void;
  onError?: (error: Error) => void;
}

export const Timeline: React.FC<TimelineProps> = ({
  events,
  orientation = 'horizontal',
  renderType = 'canvas',
  width = 800,
  height = 600,
  className = '',
  style = {},
  onReady,
  onError,
}) => {
  // Timeline configuration
  const config: TimelineConfig = {
    events,
    orientation,
    renderType,
    width,
    height,
  };

  // Use timeline hook
  const { containerRef, instance, error } = useTimeline(config);

  // Handle ready event
  React.useEffect(() => {
    if (instance && onReady) {
      onReady(instance);
    }
  }, [instance, onReady]);

  // Handle error event
  React.useEffect(() => {
    if (error && onError) {
      onError(error);
    }
  }, [error, onError]);

  // Container style
  const containerStyle: CSSProperties = {
    width: `${width}px`,
    height: `${height}px`,
    position: 'relative',
    overflow: 'hidden',
    ...style,
  };

  return (
    <div
      ref={containerRef}
      className={`ldesign-timeline ${className}`}
      style={containerStyle}
    />
  );
};

export default Timeline;

// src/adapters/vue/components/Timeline.vue
<template>
  <div ref="timelineRef" class="ldesign-timeline" :class="className" :style="customStyle"></div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { TimelineConfig, TimelineEvent } from '../../../types';
import { useTimeline } from '../composables/useTimeline';

/**
 * Props
 */
const props = withDefaults(defineProps<{
  events: TimelineEvent[];
  orientation?: 'horizontal' | 'vertical';
  renderType?: 'canvas' | 'svg';
  width?: number;
  height?: number;
  className?: string;
  style?: Record<string, string>;
}>(), {
  orientation: 'horizontal',
  renderType: 'canvas',
  width: 800,
  height: 600,
  className: '',
  style: () => ({}),
});

/**
 * Emits
 */
const emit = defineEmits<{
  ready: [instance: any];
  error: [error: Error];
}>();

// Timeline configuration
const config = computed<TimelineConfig>(() => ({
  events: props.events,
  orientation: props.orientation,
  renderType: props.renderType,
  width: props.width,
  height: props.height,
}));

// Use timeline composable
const { container, instance, error, generate } = useTimeline(ref(config.value));

// Ref for container
const timelineRef = ref<HTMLElement | null>(null);

// Custom style
const customStyle = computed(() => ({
  width: `${props.width}px`,
  height: `${props.height}px`,
  ...props.style,
}));

// Initialize
onMounted(async () => {
  container.value = timelineRef.value;
  await generate();
  if (instance.value) {
    emit('ready', instance.value);
  }
});

// Watch errors
watch(error, (err) => {
  if (err) {
    emit('error', err);
  }
});

// Expose instance
defineExpose({
  instance,
});
</script>

<style scoped>
.ldesign-timeline {
  position: relative;
  overflow: hidden;
}
</style>
